# The min for the x and z can be a negative number so -50000 is accectable default is 0
MinX: 0
MinZ: 0
MaxX: 50000
MaxZ: 50000
# Do you want to try to find a new loaction if the first on is too past the max? Default true
Retry: true
Retries: 4
#What is the message for when no suitable location is found
No Suitable Location: '&4No Suitable Locations found'
#Message to be displayed on teleport 
Teleport: '&2Thrown to a random loaction...'
#No Sign Permission Message
No-Perm: '&4You do not have permission to make a wild sign'
#Cooldoown time in seconds if you you want no cool down set it to 0
Cooldown: 5