main: me.Qball.Wild.Wild
name: Wild
version: 1.9
author: Qball_
description: Be thrown to a far away place
commands:
   wild:
    description: Be thrown to a random place
    usage:
   wildtp:
    description: Shows the help message
    usage:
permissions:
     wild.wildtp:
        description: Gives the player the abiltiy to use the /wild 
     wild.wildtp.others:
        description: Gives the player the ability to use /wild on other players
     wild.wildtp.createSign:
        description: Gives the player the ablity to make a wildtp sign
     wild.wildtp.reload:
        description: Gives the player the ablity to reload plugin config
     