# WorldTp is  optional only use if you need to have to teleport from world a to b
# Accepted default language files are english, spanish, dutch, deutsch, french, and italian.
# You can add any other language you want by making a yml in the lang file and then putting the yml file's name
# in language spot.
# Cooldown is in seconds
config-version: 400

language: english
blacklisted-biomes: [ 'OCEAN' ]
use_hooks: false
distance: 20
cost: 150
retry_limit: 10
delay: 5
TeleportNewbies: false
cooldown: 300

regions:
    world:
      minX: -100
      maxX: 100
      minZ: -100
      maxZ: 100
      worldTo: ""
portals: {}

migrated: false